/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallas;

import evaluacion.ExamenMatematica;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Mundo del Saber
 */
public class JFrameMatematicaExamen extends javax.swing.JFrame {

    private JFrameMatematica padre;

    /**
     * Creates new form JFrameMatematicaExamen
     */
    public JFrameMatematicaExamen(JFrameMatematica padre) {
        initComponents();
        transparencia();
        lblPregunta.setText(em.getPregunta(posicion));
        String[] a = em.setRespuestas(posicion);
        buttonGroup1.clearSelection(); //Sirve para borrar las selecciones
        rbOpcion1.setText(a[0]);
        rbOpcion2.setText(a[1]);
        rbOpcion3.setText(a[2]);
        rbOpcion4.setText(a[3]);
        rbOpcion1.requestFocus();
        btnAnterior.setEnabled(false);
        btnTerminar.setEnabled(false);
        this.padre = padre;
    }

    int posicion = 0;
    ExamenMatematica em = new ExamenMatematica();
    Object[] select = {"", "", "", "", "", "", "", "", "", ""};

    //Métodos
    public void siguiente() {
        if (posicion == 8) {
            btnSiguiente.setEnabled(false);
            btnTerminar.setEnabled(true);
        }

        if (posicion < 9) {
            btnAnterior.setEnabled(true);
            posicion++;
            lblPregunta.setText(em.getPregunta(posicion));
            String[] a = em.setRespuestas(posicion);
            // sirve para borrar las selecciones de los radio button
            buttonGroup1.clearSelection();
            rbOpcion1.setText(a[0]);
            rbOpcion2.setText(a[1]);
            rbOpcion3.setText(a[2]);
            rbOpcion4.setText(a[3]);
            rbOpcion1.requestFocus();
        } else {
            Toolkit.getDefaultToolkit().beep();
        }
    }

    public void anterior() {
        if (posicion == 0) {
            btnAnterior.setEnabled(false);
        }

        if (posicion > 0) {
            posicion--;
            btnSiguiente.setEnabled(true);
            lblPregunta.setText(em.getPregunta(posicion));
            String[] a = em.setRespuestas(posicion);
            // sirve para borrar las selecciones de los radio button
            buttonGroup1.clearSelection();
            rbOpcion1.setText(a[0]);
            rbOpcion2.setText(a[1]);
            rbOpcion3.setText(a[2]);
            rbOpcion4.setText(a[3]);
            rbOpcion1.requestFocus();
        } else {
            Toolkit.getDefaultToolkit().beep();
        }
    }

    public void calificar() {

        int calificacion = 0;

        for (int i = 0; i < 10; i++) {
            if (select[i].equals(em.getRespuesta(i))) {
                calificacion = calificacion + 2;
            }
        }
        JOptionPane.showMessageDialog(rootPane, "Tu calificación es "
                + calificacion);
    }

    public void regresar() {
        padre.setVisible(true);
        this.dispose();
    }

    public void transparencia() {
        btnAnterior.setOpaque(false);
        btnAnterior.setContentAreaFilled(false);
        btnAnterior.setBorderPainted(false);
        btnSiguiente.setOpaque(false);
        btnSiguiente.setContentAreaFilled(false);
        btnSiguiente.setBorderPainted(false);
        btnTerminar.setOpaque(false);
        btnTerminar.setContentAreaFilled(false);
        btnTerminar.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblPregunta = new javax.swing.JLabel();
        rbOpcion1 = new javax.swing.JRadioButton();
        rbOpcion2 = new javax.swing.JRadioButton();
        rbOpcion3 = new javax.swing.JRadioButton();
        rbOpcion4 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        btnSiguiente = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnTerminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(217, 217, 217));
        jPanel1.setPreferredSize(new java.awt.Dimension(1440, 1023));

        jPanel2.setBackground(new java.awt.Color(86, 154, 150));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setText("Mundo del Saber");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel1)
                .addContainerGap(965, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jLabel2.setBackground(new java.awt.Color(217, 217, 217));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Pregunta");

        lblPregunta.setBackground(new java.awt.Color(217, 217, 217));
        lblPregunta.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblPregunta.setForeground(new java.awt.Color(0, 0, 0));
        lblPregunta.setText("¿Pregunta 1?");

        rbOpcion1.setBackground(new java.awt.Color(217, 217, 217));
        buttonGroup1.add(rbOpcion1);
        rbOpcion1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbOpcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOpcion1ActionPerformed(evt);
            }
        });

        rbOpcion2.setBackground(new java.awt.Color(217, 217, 217));
        buttonGroup1.add(rbOpcion2);
        rbOpcion2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbOpcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOpcion2ActionPerformed(evt);
            }
        });

        rbOpcion3.setBackground(new java.awt.Color(217, 217, 217));
        buttonGroup1.add(rbOpcion3);
        rbOpcion3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbOpcion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOpcion3ActionPerformed(evt);
            }
        });

        rbOpcion4.setBackground(new java.awt.Color(217, 217, 217));
        buttonGroup1.add(rbOpcion4);
        rbOpcion4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbOpcion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOpcion4ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(80, 90, 98));

        btnSiguiente.setBackground(new java.awt.Color(80, 90, 98));
        btnSiguiente.setForeground(new java.awt.Color(80, 90, 98));
        btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/siguiente.png"))); // NOI18N
        btnSiguiente.setBorder(null);
        btnSiguiente.setBorderPainted(false);
        btnSiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnAnterior.setBackground(new java.awt.Color(80, 90, 98));
        btnAnterior.setForeground(new java.awt.Color(80, 90, 98));
        btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anterior.png"))); // NOI18N
        btnAnterior.setBorder(null);
        btnAnterior.setBorderPainted(false);
        btnAnterior.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnTerminar.setBackground(new java.awt.Color(80, 90, 98));
        btnTerminar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTerminar.setForeground(new java.awt.Color(80, 90, 98));
        btnTerminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/terminarExamen.png"))); // NOI18N
        btnTerminar.setBorder(null);
        btnTerminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(606, Short.MAX_VALUE)
                .addComponent(btnAnterior)
                .addGap(103, 103, 103)
                .addComponent(btnSiguiente)
                .addGap(316, 316, 316)
                .addComponent(btnTerminar)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSiguiente)
                    .addComponent(btnAnterior)
                    .addComponent(btnTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbOpcion1)
                    .addComponent(jLabel2)
                    .addComponent(lblPregunta)
                    .addComponent(rbOpcion2)
                    .addComponent(rbOpcion3)
                    .addComponent(rbOpcion4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addComponent(lblPregunta)
                .addGap(96, 96, 96)
                .addComponent(rbOpcion1)
                .addGap(18, 18, 18)
                .addComponent(rbOpcion2)
                .addGap(18, 18, 18)
                .addComponent(rbOpcion3)
                .addGap(18, 18, 18)
                .addComponent(rbOpcion4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 454, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbOpcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOpcion1ActionPerformed
        select[posicion] = rbOpcion1.getLabel();
    }//GEN-LAST:event_rbOpcion1ActionPerformed

    private void rbOpcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOpcion2ActionPerformed
        select[posicion] = rbOpcion2.getLabel();
    }//GEN-LAST:event_rbOpcion2ActionPerformed

    private void rbOpcion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOpcion3ActionPerformed
        select[posicion] = rbOpcion3.getLabel();
    }//GEN-LAST:event_rbOpcion3ActionPerformed

    private void rbOpcion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOpcion4ActionPerformed
        select[posicion] = rbOpcion4.getLabel();
    }//GEN-LAST:event_rbOpcion4ActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        siguiente();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        anterior();
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(null, "Desea terminar con el exámen?",
            "Mundo del Saber", JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
        if (respuesta == JOptionPane.YES_OPTION) {
            calificar();
            regresar();
        }
    }//GEN-LAST:event_btnTerminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMatematicaExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMatematicaExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMatematicaExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMatematicaExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMatematicaExamen(new JFrameMatematica(
                        new JFrameCurso(new JFrameMenuPrincipal()))).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnTerminar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblPregunta;
    private javax.swing.JRadioButton rbOpcion1;
    private javax.swing.JRadioButton rbOpcion2;
    private javax.swing.JRadioButton rbOpcion3;
    private javax.swing.JRadioButton rbOpcion4;
    // End of variables declaration//GEN-END:variables
}
